server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stocktrakr

stock:
  client:
    brapi:
      url: https://brapi.dev/api/quote
      token: wbV85vPu4sbeZQiAFzcPpJ